### ISSUE TITLE
When testing a single node, I found that following the initialization was not enough to complete the test items. Can you add more user manual content to better complete the test?

### ISSUE THREAD

**Issue by marks221b** [NVIDIA/cloudai#272]
## Problem Related to the Feature
> A clear and concise description of what the problem is.
(venv) root@gpu01:~/cloudai# cloudai run    --system-config conf/common/system/standalone_system.toml    --tests-dir conf/common/test    --test-scenario conf/common/test_scenario/nccl_test.toml
[INFO] System Name: standalone_system
[INFO] Scheduler: standalone
[INFO] Test Scenario Name: nccl-test
[INFO] Checking if test templates are installed.
[INFO] Test Scenario: nccl-test

Section Name: Tests.1
  Test Name: nccl_test_all_reduce
  Description: all_reduce
  No dependencies
Section Name: Tests.2
  Test Name: nccl_test_all_gather
  Description: all_gather
  Start Post Comp: Tests.1, Time: 0 seconds
Section Name: Tests.3
  Test Name: nccl_test_reduce_scatter
  Description: reduce_scatter
  Start Post Comp: Tests.2, Time: 0 seconds
Section Name: Tests.4
  Test Name: nccl_test_alltoall
  Description: alltoall
  Start Post Comp: Tests.3, Time: 0 seconds
Section Name: Tests.5
  Test Name: nccl_test_all_reduce
  Description: all_reduce
  Start Post Comp: Tests.4, Time: 0 seconds
Section Name: Tests.6
  Test Name: nccl_test_all_gather
  Description: all_gather
  Start Post Comp: Tests.5, Time: 0 seconds
Section Name: Tests.7
  Test Name: nccl_test_reduce_scatter
  Description: reduce_scatter
  Start Post Comp: Tests.6, Time: 0 seconds
Section Name: Tests.8
  Test Name: nccl_test_alltoall
  Description: alltoall
  Start Post Comp: Tests.7, Time: 0 seconds
Section Name: Tests.9
  Test Name: nccl_test_all_reduce
  Description: all_reduce
  Start Post Comp: Tests.8, Time: 0 seconds
Section Name: Tests.10
  Test Name: nccl_test_all_gather
  Description: all_gather
  Start Post Comp: Tests.9, Time: 0 seconds
Section Name: Tests.11
  Test Name: nccl_test_reduce_scatter
  Description: reduce_scatter
  Start Post Comp: Tests.10, Time: 0 seconds
Section Name: Tests.12
  Test Name: nccl_test_alltoall
  Description: alltoall
  Start Post Comp: Tests.11, Time: 0 seconds
Section Name: Tests.13
  Test Name: nccl_test_all_reduce
  Description: all_reduce
  Start Post Comp: Tests.12, Time: 0 seconds
Section Name: Tests.14
  Test Name: nccl_test_all_gather
  Description: all_gather
  Start Post Comp: Tests.13, Time: 0 seconds
Section Name: Tests.15
  Test Name: nccl_test_reduce_scatter
  Description: reduce_scatter
  Start Post Comp: Tests.14, Time: 0 seconds
Section Name: Tests.16
  Test Name: nccl_test_alltoall
  Description: alltoall
  Start Post Comp: Tests.15, Time: 0 seconds
Section Name: Tests.17
  Test Name: nccl_test_all_reduce
  Description: all_reduce
  Start Post Comp: Tests.16, Time: 0 seconds
Section Name: Tests.18
  Test Name: nccl_test_all_gather
  Description: all_gather
  Start Post Comp: Tests.17, Time: 0 seconds
Section Name: Tests.19
  Test Name: nccl_test_reduce_scatter
  Description: reduce_scatter
  Start Post Comp: Tests.18, Time: 0 seconds
Section Name: Tests.20
  Test Name: nccl_test_alltoall
  Description: alltoall
  Start Post Comp: Tests.19, Time: 0 seconds
Section Name: Tests.21
  Test Name: nccl_test_all_reduce
  Description: all_reduce
  Start Post Comp: Tests.20, Time: 0 seconds
Section Name: Tests.22
  Test Name: nccl_test_all_gather
  Description: all_gather
  Start Post Comp: Tests.21, Time: 0 seconds
Section Name: Tests.23
  Test Name: nccl_test_reduce_scatter
  Description: reduce_scatter
  Start Post Comp: Tests.22, Time: 0 seconds
Section Name: Tests.24
  Test Name: nccl_test_alltoall
  Description: alltoall
  Start Post Comp: Tests.23, Time: 0 seconds
[INFO] Initializing Runner [RUN] mode
[INFO] Creating StandaloneRunner
[INFO] Starting test scenario execution.
[INFO] Starting test: Tests.1
[INFO] Running test: Tests.1
Traceback (most recent call last):
  File "/root/cloudai/venv/bin/cloudai", line 8, in <module>
    sys.exit(main())
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/__main__.py", line 24, in main
    rc = cloudai_cli.run()
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/cli/cli.py", line 151, in run
    return self.handlers[args.mode](args)
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/cli/handlers.py", line 150, in handle_dry_run_and_run
    asyncio.run(runner.run())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/_core/runner.py", line 76, in run
    await self.runner.run()
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/_core/base_runner.py", line 149, in run
    await self.submit_test(tr)
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/_core/base_runner.py", line 165, in submit_test
    job = self._submit_test(tr)
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/runner/standalone/standalone_runner.py", line 57, in _submit_test
    exec_cmd = tr.test.test_template.gen_exec_command(tr)
  File "/root/cloudai/venv/lib/python3.10/site-packages/cloudai/_core/test_template.py", line 130, in gen_exec_command
    raise ValueError(
ValueError: command_gen_strategy is missing. Ensure the strategy is registered in the Registry by calling the appropriate registration function for the system type.

## Proposed Solution
> A clear and concise description of what you want to happen.

Hello everyone, can you add more instructions for single-node and multi-node in the user documentation?
Thanks for all.

**Comment by amaslenn** [comment]
Thank you @marks221b for reporting this issue!

Our `standalone` System is not supporting running any tests besides `sleep`. It was designed as an example mainly.

Anyway, I'll work on improving the documentation to have support matrix.

Please let me know if you have any follow up questions.
